Repository Code-Poets/project-liberation, pull requests merged in 2019-11, with the labels that each got.

#94 Bugfix remove learn more
  company_website/static/main_page/services.sass
  company_website/templates/main_page_partials/services.haml
Labels: bug

#95 Bugfix portfolio section
  company_website/static/common/scripts/aos_init.js
  company_website/static/main_page/portfolio.sass
  company_website/templates/main_page_partials/portfolio.haml
Labels: bug

#99 Bugfix change animations in team-introduction subpage
  company_website/templates/team_introduction_page_partials/company_introduction.haml
  company_website/templates/team_introduction_page_partials/employees_introduction.haml
Labels: bug

#100 Bugfix Delete unecessary calc() function from sass files
  company_website/static/team_introduction_page/company_introduction.sass
Labels: bug

#101 Bugfix popular article border
  blog/static/blog_posts_list/blog_posts_list.sass
  blog/templates/blog/blog_posts_list.haml
Labels: bug

#104 Bugfix animations display
  company_website/static/common/scripts/aos_init.js
  company_website/templates/main_page_partials/about_us.haml
  company_website/templates/main_page_partials/map_navigator.haml
  company_website/templates/main_page_partials/portfolio.haml
  company_website/templates/main_page_partials/ready_to_work_with_us.haml
  company_website/templates/main_page_partials/testimonials.haml
Labels: bug

#105 Bugfix about us section
  company_website/static/main_page/about_us.sass
  company_website/templates/main_page_partials/about_us.haml
Labels: bug

#97 Place Google API call after all other scripts
  company_website/templates/main_page.haml
  company_website/templates/main_page_partials/scripts.haml
Labels: bug

#106 Bugfix blog display on mobile devices
  blog/static/blog_posts_list/blog_posts_list.sass
  blog/static/blog_posts_list/partials/_main_article.sass
  blog/templates/blog/blog_posts_list.haml
  blog/templates/blog/partials/article_list.haml
Labels: bug

#109 Change margin direction on blog menu
  blog/static/blog/blog_menu.sass
Labels: bug

#110 Bugfix center text in promo div in edge
  company_website/static/career/become_part_of_our_team.sass
Labels: bug

#112 Bugfix width and margins about_us secion on edge
  company_website/static/main_page/about_us.sass
Labels: bug

#111 Add script to resize testimonials according to container height
  company_website/static/common/scripts/responsiveness_helpers.js
  company_website/static/main_page/testimonials.sass
Labels: bug

#114 Bugfix add clutch badge on main screen
  company_website/static/main_page/main_screen.sass
  company_website/templates/main_page_partials/main_screen.haml
Labels: bug

#117 Bugfix blog post limit
  blog/models.py
Labels: bug

#118 Match testimonials sizing to the rest of the page
  company_website/static/main_page/scripts/owl_carousel.js
  company_website/static/main_page/testimonials.sass
  company_website/templates/main_page_partials/testimonials.haml
Labels: bug

#120 Bugfix articles order
  RELEASE-NOTES.md
  blog/models.py
Labels: bug

#122 Bugfix change directory where script should search tests
  run-test-coverage.sh
Labels: bug

#127 Feature add markdown to blog post
  Pipfile
  Pipfile.lock
  blog/migrations/0004_auto_20191118_1328.py
  blog/models.py
  project_liberation/settings/base.py
Labels: feature

#128 Feature add unlinked models to admin panel
  company_website/admin.py
  company_website/models.py
Labels: feature

#130 Chore refactor ProjectToEstimate model
  company_website/admin.py
  company_website/constants.py
  company_website/forms.py
  company_website/migrations/0004_auto_20191115_1155.py
  company_website/models.py
Labels: chore

#129 Feature Change Blockchain service to Cheminformatic service
  company_website/static/main_page/services.sass
  company_website/templates/main_page_partials/services.haml
Labels: feature

#126 Fix jQuery issues in how we work page
  company_website/templates/how_we_work_page.haml
Labels: bug

#131 Chore add release notes for v1.2.0 tag
  RELEASE-NOTES.md
Labels: chore

#133 Feature ehange technologies images
  company_website/templates/main_page_partials/technologies.haml
Labels: feature

#134 Bugfix change `cheminformatic` to `cheminformatics`
  company_website/templates/main_page_partials/services.haml
Labels: bug

#141 Feature add meta tags for blog posts
  blog/templates/blog_post.haml
  company_website/templates/base.haml
Labels: feature

#137 Add a playbook that deploys a new version of project-liberation to the server
  project_liberation_deployment/consts.yml
  project_liberation_deployment/deploy.yml
  project_liberation_deployment/roles/configure_project_liberation_environment/defaults/main.yml
  project_liberation_deployment/roles/configure_project_liberation_environment/tasks/generate-static-files.yml
  project_liberation_deployment/roles/configure_project_liberation_environment/tasks/main.yml
  project_liberation_deployment/roles/configure_project_liberation_environment/tasks/migrate-database.yml
  project_liberation_deployment/roles/configure_project_liberation_environment/tasks/update-project-liberation-application.yml
  project_liberation_deployment/roles/configure_project_liberation_environment/tasks/upload-image-package.yml
  project_liberation_deployment/roles/configure_project_liberation_environment/tasks/upload-secret-file.yml
  project_liberation_deployment/roles/configure_project_liberation_environment/templates/local_settings.py.j2
  project_liberation_deployment/roles/maintenance_mode/tasks/disable-maintenance-mode.yml
  project_liberation_deployment/roles/maintenance_mode/tasks/enable-maintenance-mode.yml
  project_liberation_deployment/roles/maintenance_mode/tasks/main.yml
Labels: feature

#139 Change navbar's bottom from solid border to shadow
  company_website/static/common/menu.sass
  company_website/templates/common_partials/menu.haml
Labels: feature

#124 Fix testimonials' carousel autoplay behaviour
  company_website/static/main_page/scripts/owl_carousel.js
Labels: bug

#144 Bugfix Estimate Project
  company_website/forms.py
  company_website/static/estimate_project/estimate_project.sass
  company_website/static/estimate_project/scripts/estimate_form.js
  company_website/templates/estimate_project/estimate_project_form.haml
Labels: bug

#145 Feature change main screen slogan
  company_website/templates/main_page_partials/main_screen.haml
Labels: feature

#143 Chore modify the ip address after the domain has been attached to the server
  download-and-add-images-to-django.sh
Labels: chore

#147 Bugfix estimate project url
  company_website/templates/common_partials/menu.haml
  company_website/urls.py
Labels: bug

#149 Feature add alt and title parameters to img tag
  blog/templates/blog/partials/article_list.haml
  blog/templates/blog/partials/search_form.haml
  blog/templates/blog/post.haml
  company_website/templates/base.haml
  company_website/templates/career_partials/become_part_of_our_team.haml
  company_website/templates/career_partials/perk.haml
  company_website/templates/career_partials/perks_and_benefits.haml
  company_website/templates/common_partials/footer.haml
  company_website/templates/common_partials/menu.haml
  company_website/templates/estimate_project/estimate_project_form.haml
  company_website/templates/how_we_work_partials/how_we_work_partial.haml
  company_website/templates/how_we_work_partials/scrum_metodology.haml
  company_website/templates/how_we_work_partials/time_materials_fixed_price_graph.haml
  company_website/templates/main_page_partials/main_screen.haml
  company_website/templates/main_page_partials/portfolio.haml
  company_website/templates/main_page_partials/ready_to_work_with_us.haml
  company_website/templates/main_page_partials/services.haml
  company_website/templates/main_page_partials/technologies.haml
  company_website/templates/main_page_partials/testimonials.haml
  company_website/templates/team_introduction_page_partials/company_introduction.haml
  company_website/templates/team_introduction_page_partials/employees_introduction.haml
Labels: feature

#150 Bugfix estimate project view url regex
  company_website/urls.py
Labels: feature

#152 Feature add meta tags for social medias
  blog/templates/blog_post.haml
Labels: feature

#153 Feature change services order
  company_website/templates/main_page_partials/services.haml
Labels: feature

#154 Feature change elements in menu
  company_website/templates/common_partials/menu.haml
Labels: feature

#151 Feature add restricting access based on country
  project_liberation_deployment/roles/configure_nginx/templates/maintenance.j2
  project_liberation_deployment/roles/configure_nginx/templates/project-liberation.j2
Labels: feature

#155 Bugfix blog app model
  blog/models.py
Labels: bug

#156 Make textarea's background feather ignore user inputs in Estimate Project page
  company_website/static/estimate_project/estimate_project.sass
  company_website/templates/main_page_partials/ready_to_work_with_us.haml
Labels: bug

#157 Add sitemap for whole project
  blog/models.py
  blog/sitemap.py
  common/custom_sitemap.py
  company_website/sitemap.py
  project_liberation/settings/base.py
  project_liberation/urls.py
Labels: feature

#160 Chore url refactor
  blog/urls.py
  project_liberation/urls.py
Labels: chore

#161 Bugfix blog models errors
  blog/models.py
Labels: bug
