Repository Code-Poets/project-liberation, pull requests merged in 2019-10, with the labels that each got.

#22 Feature add services template
  company_website/static/main_page/partials/_constants.sass
  company_website/static/main_page/services.sass
  company_website/templates/main_page/services.haml
Labels: feature

#24 Feature add ready to work with us section
  company_website/static/main_page/partials/_constants.sass
  company_website/static/main_page/ready_to_work_with_us.sass
  company_website/static/main_page/section_separator.sass
  company_website/templates/main_page/partials/section_separator.haml
  company_website/templates/main_page/ready_to_work_with_us.haml
Labels: feature

#38 Chore fix fullcheck settings
  find-files-to-check.sh
  run-test-coverage.sh
Labels: chore

#40 Chore add ico to .gitignore
  .gitignore
Labels: chore

#44 Add lazy loading to all images
  company_website/templates/common_partials/footer.haml
  company_website/templates/common_partials/head.haml
  company_website/templates/common_partials/menu.haml
  company_website/templates/main_page_partials/main_screen.haml
  company_website/templates/main_page_partials/ready_to_work_with_us.haml
  company_website/templates/main_page_partials/services.haml
  company_website/templates/main_page_partials/technologies.haml
Labels: feature

#45 Chore change location of menu and footer images
  company_website/templates/common_partials/footer.haml
  company_website/templates/common_partials/menu.haml
Labels: chore

#43 Fix responsiveness for ready to work with us template
  company_website/static/main_page/ready_to_work_with_us.sass
  company_website/templates/main_page_partials/ready_to_work_with_us.haml
Labels: bug

#50 Add ids and links to menu elements
  company_website/templates/common_partials/menu.haml
  company_website/templates/main_page_partials/about_us.haml
  company_website/templates/main_page_partials/main_screen.haml
  company_website/templates/main_page_partials/portfolio.haml
  company_website/templates/main_page_partials/ready_to_work_with_us.haml
  company_website/templates/main_page_partials/services.haml
Labels: feature

#55 Chore extract `base.haml` from other pages
  company_website/static/common/scripts/aos_init.js
  company_website/templates/base.haml
  company_website/templates/common_partials/scripts.haml
  company_website/templates/main_page.haml
  company_website/templates/main_page_partials/scripts.haml
  company_website/templates/team_introduction_page.haml
Labels: chore

#62 Bugfix clarify separators
  company_website/static/common/partials/_constants.sass
  company_website/static/main_page/about_us.sass
  company_website/static/main_page/portfolio.sass
  company_website/templates/common_partials/menu.haml
  company_website/templates/main_page_partials/about_us.haml
  company_website/templates/main_page_partials/portfolio.haml
  company_website/templates/main_page_partials/ready_to_work_with_us.haml
  company_website/templates/main_page_partials/services.haml
  company_website/templates/main_page_partials/technologies.haml
  company_website/templates/main_page_partials/testimonials.haml
Labels: bug

#63 Bugfix add talk with Adrian popup
  company_website/static/main_page/ready_to_work_with_us.sass
  company_website/static/main_page/scripts/talk_with_adrian_popup.js
  company_website/templates/main_page_partials/head.haml
  company_website/templates/main_page_partials/ready_to_work_with_us.haml
  company_website/templates/main_page_partials/scripts.haml
Labels: bug

#64 Bugfix add links to codepoets logo
  company_website/templates/common_partials/menu.haml
Labels: bug

#65 Bugfix remove home from menu
  company_website/templates/common_partials/menu.haml
Labels: bug

#67 Bugfix navbar navigation on scroll
  company_website/static/common/scripts/menu_functionality.js
Labels: bug

#68 Bugfix estimate project button
  company_website/static/main_page/ready_to_work_with_us.sass
  company_website/templates/main_page_partials/ready_to_work_with_us.haml
Labels: bug

#69 Bugfix add logo on mobile and fix border radius
  company_website/static/main_page/main_screen.sass
  company_website/templates/main_page_partials/main_screen.haml
Labels: bug

#70 Bugfix fix display technologies on mobile
  company_website/static/main_page/technologies.sass
Labels: bug

#71 Bugfix add animation functionality on menu click
  company_website/static/common/scripts/menu_functionality.js
Labels: bug
