Repository Code-Poets/project-liberation, pull requests merged in 2019-12, with the labels that each got.

#165 Add tests for BlogIndexPage methods
  blog/tests/test_blog_pages_integration.py
Labels: chore

#166 Bugfix dates in articles list view
  blog/tests/test_blog_pages_integration.py
  project_liberation/settings/base.py
Labels: bug

#167 Feature add is_working field in Employees model
  company_website/admin.py
  company_website/migrations/0006_employees_is_working.py
  company_website/models.py
  company_website/tests/test_views.py
  company_website/views.py
Labels: feature

#168 Chore add developers scripts
  reload-db-static.sh
  reload-statics.sh
Labels: chore

#171 Bugfix typo in project liberation bucket name
  project_liberation_deployment/consts.yml
  project_liberation_deployment/roles/backup/templates/project-liberation-media-content-backup.sh.j2
Labels: bug

#172 Add a long cache lifetime after implementing the static files versioning mechanism
  project_liberation_deployment/roles/configure_nginx/templates/project-liberation.j2
Labels: feature

#173 Chore move sentry app to production settings
  project_liberation/settings/base.py
  project_liberation/settings/production.py
Labels: chore

#176 Bugfix add absolute url to blog posts
  blog/templates/blog_post.haml
Labels: bug

#178 Bugfix fix javascript files in cached static files
  project_liberation/settings/base.py
Labels: bug

#177 Move order of tasks to add images to django before generate static files
  project_liberation_deployment/roles/configure_project_liberation_environment/tasks/generate-static-files.yml
Labels: bug

#180 Bugfix menu collapse too late
  company_website/static/common/menu.sass
  company_website/static/common/partials/_constants.sass
  company_website/static/common/partials/_hamburger_menu.sass
  company_website/static/common/scripts/menu_functionality.js
Labels: bug

#181 Revert "Merge branch 'feature-add-loading-different-sizes-of-images-depend-on-screen-size
  company_website/static/how_we_work/how_we_work.sass
  company_website/templates/career_partials/become_part_of_our_team.haml
  company_website/templates/career_partials/perk.haml
  company_website/templates/career_partials/perks_and_benefits.haml
  company_website/templates/how_we_work_partials/how_we_work_partial.haml
  company_website/templates/how_we_work_partials/scrum_metodology.haml
  company_website/templates/main_page_partials/about_us.haml
  company_website/templates/main_page_partials/main_screen.haml
  company_website/templates/main_page_partials/portfolio.haml
  company_website/templates/main_page_partials/technologies.haml
  company_website/templates/team_introduction_page_partials/company_introduction.haml
  company_website/templatetags/static_path.py
  project_liberation/settings/base.py
  project_liberation/settings/production.py
Labels: revert

#183 Bugfix estimate project section header
  company_website/static/estimate_project/estimate_project.sass
Labels: bug

#185 Chore delete XFrameOptionsMiddleware
  project_liberation/settings/base.py
Labels: chore

#186 Chore add Pipeline settings to development.py
  project_liberation/settings/development.py
Labels: chore

#187 Bugfix change size when menu from desktop should change to mobile
  blog/static/blog/blog_menu.sass
Labels: bug

#188 Chore add limit rate and connection limit per client for download endpoint
  project_liberation_deployment/roles/configure_nginx/templates/project-liberation.j2
Labels: chore

#193 Feature change number of popular articles to five
  blog/models.py
  blog/tests/test_blog_pages_integration.py
Labels: feature

#196 Add new section header for employees introduction subpage
  company_website/static/common/partials/_constants.sass
  company_website/static/team_introduction_page/employees_introduction.sass
  company_website/templates/team_introduction_page_partials/employees_introduction.haml
Labels: feature

#125 Add missing system checks for custom storage directories
  project_liberation/system_check.py
  project_liberation/tests/test_system_checks.py
Labels: chore

#198 Bugfix empty space between testimonials and ready to work with us on main page.
  company_website/static/main_page/testimonials.sass
Labels: bug

#201 Bugfix position name look on team-introduction page
  company_website/static/team_introduction_page/employees_introduction.sass
Labels: bug

#202 Fix inconsistent section padding in main page.
  company_website/static/main_page/about_us.sass
  company_website/static/main_page/clutch_award.sass
  company_website/static/main_page/portfolio.sass
  company_website/static/main_page/ready_to_work_with_us.sass
  company_website/static/main_page/services.sass
  company_website/static/main_page/testimonials.sass
  company_website/templates/main_page_partials/ready_to_work_with_us.haml
Labels: bug

#203 Feature add animation to who are we part in team introduction page
  company_website/static/team_introduction_page/scripts/read-more.js
Labels: feature

#204 Chore add loading test data to testimonials
  common/helpers.py
  project_liberation/management/commands/load_initial_data.py
Labels: chore
