Repository Code-Poets/project-liberation, pull requests merged in 2020-07, with the labels that each got.

#241 Feature add thank you page
  company_website/constants.py
  company_website/migrations/0007_auto_20200625_1652.py
  company_website/static/common/partials/_constants.sass
  company_website/static/thank_you/scripts/timed_redirect.js
  company_website/static/thank_you/thank_you.sass
  company_website/templates/thank_you.haml
  company_website/templates/thank_you/thank_you.haml
  company_website/tests/test_views.py
  company_website/urls.py
  company_website/views.py
  project_liberation/settings/base.py
Labels: feature

#243 Feature remove categories from blog
  blog/category/templates/index.html
  blog/migrations/0012_auto_20200625_1631.py
  blog/models.py
  blog/sitemap.py
  blog/static/blog/blog_menu.sass
  blog/static/blog/scripts/blog_menu.js
  blog/static/blog_post/blog_post.sass
  blog/static/blog_posts_list/blog_posts_list.sass
  blog/static/blog_posts_list/partials/_main_article.sass
  blog/templates/blog/blog_menu.haml
  blog/templates/blog/blog_posts_list.haml
  blog/templates/blog/blog_posts_list_partials/main_article.haml
  blog/templates/blog/category_posts.haml
  blog/templates/blog/partials/article_list.haml
  blog/templates/blog/post.haml
  blog/templates/blog_categories_posts.haml
  blog/tests/test_blog_article_page.py
  blog/tests/test_blog_category_page.py
  blog/tests/test_blog_pages_integration.py
  blog/tests/test_helpers.py
  lint.sh
  project_liberation/management/commands/load_initial_data.py
  project_liberation/urls.py
Labels: feature

#247 Change name of the Clutch badge image
  company_website/templates/main_page_partials/clutch_award.haml
  company_website/templates/main_page_partials/main_screen.haml
Labels: chore

#249 Bugfix blog main page layout
  blog/static/blog/blog_menu.sass
  blog/static/blog_posts_list/blog_posts_list.sass
  blog/static/blog_posts_list/partials/_main_article.sass
Labels: bug

#251 Feature change calendly link
  RELEASE-NOTES.md
  company_website/static/main_page/scripts/talk_with_adrian_popup.js
  package-lock.json
  package.json
  pyproject.toml
Labels: feature

#253 Feature update text at how we work
  company_website/static/how_we_work/how_we_work.sass
  company_website/static/how_we_work/partials/time_materials_fixed_price_graph.sass
  company_website/templates/how_we_work_partials/how_we_work_partial.haml
  company_website/templates/how_we_work_partials/time_materials_fixed_price_graph.haml
Labels: feature

#245 Feature change text and layout at blog
  blog/constants.py
  blog/models.py
  blog/static/blog/blog_menu.sass
  blog/static/blog_post/blog_post.sass
  blog/static/blog_posts_list/blog_posts_list.sass
  blog/static/blog_posts_list/partials/_main_article.sass
  blog/templates/blog/blog_posts_list.haml
  blog/templates/blog/blog_posts_list_partials/main_article.haml
  blog/templates/blog/popular_articles.haml
  blog/templates/blog_post_search_results.haml
  blog/tests/test_blog_article_page.py
  blog/tests/test_blog_pages_integration.py
  company_website/static/common/menu.sass
  company_website/static/common/partials/_constants.sass
Labels: feature

#244 Chore update project dependencies
  blog/models.py
  common/__init__.py
  common/helpers.py
  poetry.lock
  pylintrc
  pytest.ini
  requirements-dev.txt
  requirements.txt
Labels: chore

#255 Chore update dependencies
  poetry.lock
  requirements-dev.txt
  requirements.txt
  update-dependecies-files.sh
Labels: chore
