Repository Code-Poets/project-liberation, pull requests merged in 2020-03, with the labels that each got.

#224 Add google tag manager scripts
  company_website/templates/common_partials/head.haml
  company_website/templates/main_page_partials/head.haml
Labels: feature

#225 Adjust "right-container" for firefox
  company_website/static/main_page/clutch_award.sass
Labels: bug

#230 Fix /how-we-work/ page stylistic errors
  company_website/templates/how_we_work_partials/time_materials_fixed_price_graph.haml
Labels: chore

#229 Bugfix enhanced pagespeed insights
  company_website/static/main_page/map_navigator.sass
  company_website/static/main_page/scripts/map_navigator.js
  company_website/templates/main_page.haml
  company_website/templates/main_page_partials/main_screen.haml
  company_website/templates/main_page_partials/testimonials.haml
Labels: bug

#232 Chore update requirements
  poetry.lock
  requirements-dev.txt
  requirements.txt
Labels: chore

#233 Bugfix delete calendly integrity hash
  RELEASE-NOTES.md
  company_website/templates/main_page_partials/head.haml
Labels: bug
