Repository Code-Poets/project-liberation, pull requests merged in 2020-12, with the labels that each got.

#246 Feature redesign projects section
  company_website/static/main_page/portfolio.sass
  company_website/static/main_page/scripts/disableScroll.js
  company_website/static/main_page/scripts/projectHighlight.js
  company_website/static/main_page/scripts/show_more_functionality.js
  company_website/templates/base.haml
  company_website/templates/main_page_partials/portfolio.haml
  company_website/templates/main_page_partials/scripts.haml
Labels: feature

#289 Feature add playbook to the website
  company_website/static/how_we_work/how_we_work.sass
  company_website/static/how_we_work/scripts/imgPopup.js
  company_website/static/how_we_work/scripts/img_popup.js
  company_website/templates/how_we_work_partials/how_we_work_partial.haml
Labels: feature

#293 Bugfix clutch logos on mobile
  company_website/templates/main_page_partials/main_screen.haml
Labels: bug

#294 Bugfix mistake in word in team section
  company_website/templates/team_introduction_page_partials/company_introduction.haml
Labels: bug

#295 Chore update project dependencies
  company_website/factories.py
  poetry.lock
  project_liberation/settings/base.py
  pyproject.toml
  requirements-dev.txt
  requirements.txt
  style.sh
Labels: chore

#296 Bugfix google ads and tag manager setup
  blog/models.py
  company_website/static/common/scripts/head/google_tag_manager.js
  company_website/templates/common_partials/head.haml
  company_website/templates/main_page_partials/head.haml
  company_website/view_helpers.py
  project_liberation/settings/development.py
  project_liberation/settings/production.py
Labels: bug

#297 Feature redesign estimate project form
  company_website/admin.py
  company_website/forms.py
  company_website/migrations/0011_auto_20201202_0918.py
  company_website/models.py
  company_website/static/estimate_project/estimate_project.sass
  company_website/static/estimate_project/scripts/estimate_form.js
  company_website/static/estimate_project/scripts/head/conversion_tracking.js
  company_website/static/estimate_project/scripts/unifyRequiredInfoStyle.js
  company_website/templates/estimate_project.haml
  company_website/templates/estimate_project/estimate_project_email.html
  company_website/templates/estimate_project/estimate_project_form.haml
  company_website/tests/test_send_email_utils.py
  company_website/tests/test_views.py
  company_website/views.py
Labels: feature

#298 Feature add 2 additional email addresses
  project_liberation_deployment/roles/configure_project_liberation_environment/templates/local_settings.py.j2
Labels: feature

#299 Bugfix linkedin share
  blog/templates/blog_post.haml
  company_website/templates/base.haml
Labels: bug

#285 Feature add image captions
  blog/factories.py
  blog/migrations/0017_add_new_body_with_captioned_image_to_blogarticlepage_body.py
  blog/migrations/0018_migrate_blockarticlepage_body_data_to_new_body.py
  blog/migrations/0019_replace_blogarticlepage_body_field.py
  blog/models.py
  blog/static/blog_post/blog_post.sass
  blog/templates/blog/blocks/captioned_image.haml
  blog/tests/test_blog_article_page.py
Labels: feature

#300 Bugfix change order of projects in portfolio
  company_website/templates/main_page_partials/portfolio.haml
Labels: bug

#301 Bugfix change titles of elements on estimate project
  company_website/static/estimate_project/estimate_project.sass
  company_website/templates/estimate_project/estimate_project_form.haml
Labels: bug

#304 Bugfix footer at bottom on estimate project page
  company_website/static/common/footer.sass
  company_website/static/estimate_project/estimate_project.sass
Labels: bug

#305 Bugfix unify section headers on safari
  company_website/static/main_page/portfolio.sass
  company_website/static/main_page/ready_to_work_with_us.sass
  company_website/static/main_page/services.sass
Labels: bug

#303 Feature add bios for blog authors
  blog/static/blog/scripts/showAuthorBio.js
  blog/static/blog_post/blog_post.sass
  blog/static/blog_posts_list/blog_posts_list.sass
  blog/static/blog_posts_list/partials/_main_article.sass
  blog/templates/blog/blog_posts_list.haml
  blog/templates/blog/blog_posts_list_partials/main_article.haml
  blog/templates/blog/partials/article_list.haml
  blog/templates/blog/partials/author_bio.haml
  blog/templates/blog/post.haml
  company_website/migrations/0012_employees_bio.py
  company_website/models.py
Labels: feature

#302 Feature replace projects graphics
  company_website/static/main_page/portfolio.sass
  company_website/templates/main_page_partials/portfolio.haml
Labels: feature

#308 Bugfix author bio not display
  RELEASE-NOTES.md
  blog/static/blog/scripts/showAuthorBio.js
  package-lock.json
  package.json
  pyproject.toml
Labels: bug

#309 Bugfix photo in author bio
  blog/static/blog_post/blog_post.sass
  blog/static/blog_posts_list/blog_posts_list.sass
  blog/static/blog_posts_list/partials/_main_article.sass
Labels: bug

#310 Feature update email notifications
  company_website/constants.py
  company_website/send_emails_utils.py
  company_website/templates/estimate_project/estimate_project_email.html
  company_website/tests/test_send_email_utils.py
  company_website/tests/test_views.py
Labels: feature
