Repository Code-Poets/project-liberation, pull requests merged in 2020-09, with the labels that each got.

#266 Delete allowed ip addresses for admin panel
  project_liberation_deployment/roles/configure_nginx/templates/project-liberation.j2
Labels: feature

#263 Update Services and Industry Focus.
  company_website/static/main_page/industry_focus.sass
  company_website/static/main_page/services.sass
  company_website/templates/main_page_partials/industry_focus.haml
  company_website/templates/main_page_partials/services.haml
Labels: feature

#264 Feature add table of contents to blog article
  blog/migrations/0014_auto_20200908_1058.py
  blog/models.py
  blog/static/blog_post/blog_post.sass
  blog/static/blog_post/scripts/table_of_contents_smooth_scroll.js
  blog/templates/blog/post.haml
  blog/templatetags/__init__.py
  blog/templatetags/blog_article_page_filters.py
  blog/tests/test_blog_article_page.py
  blog/tests/test_helpers.py
Labels: feature

#269 Feature change social media icons order
  company_website/static/common/footer.sass
  company_website/templates/common_partials/footer.haml
Labels: feature

#268 Bugfix blog article text formatting
  blog/static/blog_post/blog_post.sass
  blog/templates/blog/post.haml
Labels: bug

#270 Bugfix main article can be taken down
  blog/models.py
  blog/templates/blog/blog_posts_list.haml
  blog/templates/blog_post_search_results.haml
  blog/tests/test_blog_article_page.py
  blog/tests/test_blog_pages_integration.py
  company_website/templates/estimate_project/success_message.haml
Labels: bug

#271 Bugfix new tab opening for external links
  company_website/static/common/scripts/external-links-handler.js
  company_website/templates/career_partials/become_part_of_our_team.haml
  company_website/templates/common_partials/footer.haml
  company_website/templates/main_page_partials/portfolio.haml
Labels: bug

#273 Bugfix recommended article deletion
  blog/models.py
  blog/tests/test_blog_article_page.py
Labels: bug

#265 Feature automated article description
  blog/constants.py
  blog/migrations/0016_remove_blogarticlepage_intro.py
  blog/models.py
  blog/templates/blog/partials/article_list.haml
  blog/templates/blog/post.haml
  blog/tests/test_blog_article_page.py
  blog/tests/test_blog_pages_integration.py
  blog/tests/test_helpers.py
  project_liberation/management/commands/load_initial_data.py
Labels: feature

#274 Bugfix table of contents scroll
  blog/static/blog_post/scripts/table_of_contents_smooth_scroll.js
Labels: bug

#275 Bugfix markdown support for intro
  blog/models.py
  blog/templates/blog/blog_posts_list_partials/main_article.haml
  blog/tests/test_blog_article_page.py
Labels: bug

#276 Chore bump version
  RELEASE-NOTES.md
  package-lock.json
  package.json
  pyproject.toml
Labels: chore
