Repository Code-Poets/project-liberation, pull requests merged in 2020-10, with the labels that each got.

#278 Feature add new certificate
  project_liberation_deployment/configure-project-liberation-server.yml
  project_liberation_deployment/consts.yml
  project_liberation_deployment/roles/backup/tasks/main.yml
  project_liberation_deployment/roles/configure_nginx/tasks/main.yml
  project_liberation_deployment/roles/configure_nginx/templates/maintenance.j2
  project_liberation_deployment/roles/configure_nginx/templates/project-liberation.j2
  project_liberation_deployment/roles/install_dependencies_and_basic_configuration/tasks/main.yml
  project_liberation_deployment/versions.yml
Labels: feature

#277 Chore refactor load initial data
  blog/factories.py
  blog/tests/__init__.py
  blog/tests/test_factories.py
  poetry.lock
  project_liberation/management/commands/load_initial_data.py
  project_liberation/tests/test_load_initial_data.py
  pyproject.toml
Labels: chore

#281 Feature change employees names display
  blog/templates/blog/blog_posts_list.haml
  blog/templates/blog/blog_posts_list_partials/main_article.haml
  blog/templates/blog/partials/article_list.haml
  blog/templates/blog/post.haml
  company_website/admin.py
  company_website/factories.py
  company_website/migrations/0009_auto_20201019_1425.py
  company_website/models.py
  company_website/templates/team_introduction_page_partials/employees_introduction.haml
Labels: feature

#279 Bugfix main page navigation
  company_website/static/common/partials/_constants.sass
  company_website/static/common/scripts/menu_functionality.js
  company_website/static/main_page/industry_focus.sass
  company_website/static/main_page/portfolio.sass
  company_website/static/main_page/ready_to_work_with_us.sass
  company_website/static/main_page/services.sass
  company_website/templates/common_partials/menu.haml
  company_website/templates/main_page_partials/main_screen.haml
  company_website/templates/main_page_partials/portfolio.haml
  company_website/templates/main_page_partials/testimonials.haml
Labels: bug

#280 Add default root page parent to BlogIndexPageFactory
  blog/factories.py
  blog/tests/test_factories.py
  project_liberation/management/commands/load_initial_data.py
Labels: bug

#282 Feature remove map
  company_website/static/main_page/map_navigator.sass
  company_website/static/main_page/scripts/map_navigator.js
  company_website/templates/common_partials/footer.haml
  company_website/templates/main_page.haml
  company_website/templates/main_page_partials/map_navigator.haml
Labels: feature

#254 Feature remove blog comment section
  blog/static/blog_post/scripts/disqus_script.js
  blog/templates/blog/post.haml
Labels: feature
